# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sriru', '0032_auto_20150319_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedata',
            name='sanctioned_head',
        ),
        migrations.RemoveField(
            model_name='fellowship',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='project',
            name='PI',
        ),
        migrations.RemoveField(
            model_name='project',
            name='co_PI',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cost_submitted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fellowship',
        ),
        migrations.DeleteModel(
            name='Fellowship',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sanction_limit',
        ),
        migrations.RemoveField(
            model_name='project_unapproved',
            name='PI',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='project_unapproved',
            name='cost_submitted',
        ),
        migrations.DeleteModel(
            name='ExpenseData',
        ),
        migrations.DeleteModel(
            name='Project_Unapproved',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='est_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sanctioned_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.RemoveField(
            model_name='purchase_type',
            name='others',
        ),
        migrations.RemoveField(
            model_name='purchase_type',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Purchase_Type',
        ),
        migrations.DeleteModel(
            name='Sanctioned_Head',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='sponsor',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
